version: 2.1

orbs:
    heroku: circleci/heroku@1.0.1

jobs:
    build:
        docker:
            - image: 'circleci/node:12.4.0'
        steps:
            - checkout
            - heroku/install
            - run:
                  name: install
                  command: 'npm install'
            - run:
                  name: lint
                  command: 'npm run lint'
            - heroku/deploy-via-git
